/*
 * Generated from Session.proto using proto2js (v3.8.2):
 *   proto2js Session.proto -commonjs >SessionProtos.js
 * 
 * DO NOT EDIT THIS FILE
 */

module.exports = require("protobufjs").newBuilder({})["import"]({
    "package": "textsecure",
    "messages": [
        {
            "name": "SessionStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "sessionVersion",
                    "id": 1
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "localIdentityKey",
                    "id": 2
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "remoteIdentityKey",
                    "id": 3
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "rootKey",
                    "id": 4
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "previousCounter",
                    "id": 5
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "Chain",
                    "name": "sendingChain",
                    "id": 6
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "KeyPair",
                    "name": "senderRatchetKeyPair",
                    "id": 7
                },
                {
                    "rule": "repeated",
                    "options": {},
                    "type": "RChain",
                    "name": "receivingChains",
                    "id": 8
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "PendingKeyExchange",
                    "name": "pendingKeyExchange",
                    "id": 9
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "PendingPreKey",
                    "name": "pendingPreKey",
                    "id": 10
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "remoteRegistrationId",
                    "id": 11
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "localRegistrationId",
                    "id": 12
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "theirBaseKey",
                    "id": 13
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bool",
                    "name": "needsRefresh",
                    "id": 14
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "aliceBaseKey",
                    "id": 15
                }
            ],
            "enums": [],
            "messages": [
                {
                    "name": "Chain",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "uint32",
                            "name": "index",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "key",
                            "id": 2
                        },
                        {
                            "rule": "repeated",
                            "options": {},
                            "type": "MessageKey",
                            "name": "messageKeys",
                            "id": 3
                        }
                    ],
                    "enums": [],
                    "messages": [
                        {
                            "name": "MessageKey",
                            "fields": [
                                {
                                    "rule": "optional",
                                    "options": {},
                                    "type": "uint32",
                                    "name": "index",
                                    "id": 1
                                },
                                {
                                    "rule": "optional",
                                    "options": {},
                                    "type": "bytes",
                                    "name": "cipherKey",
                                    "id": 2
                                },
                                {
                                    "rule": "optional",
                                    "options": {},
                                    "type": "bytes",
                                    "name": "macKey",
                                    "id": 3
                                },
                                {
                                    "rule": "optional",
                                    "options": {},
                                    "type": "bytes",
                                    "name": "iv",
                                    "id": 4
                                }
                            ],
                            "enums": [],
                            "messages": [],
                            "options": {},
                            "oneofs": {}
                        }
                    ],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "RChain",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "theirEphemeralKey",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "SessionStructure.Chain",
                            "name": "chain",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "KeyPair",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "public",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "private",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "PendingKeyExchange",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "uint32",
                            "name": "sequence",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localBaseKey",
                            "id": 2
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localBaseKeyPrivate",
                            "id": 3
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localRatchetKey",
                            "id": 4
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localRatchetKeyPrivate",
                            "id": 5
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localIdentityKey",
                            "id": 7
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "localIdentityKeyPrivate",
                            "id": 8
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "PendingPreKey",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "uint32",
                            "name": "preKeyId",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "int32",
                            "name": "signedPreKeyId",
                            "id": 3
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "baseKey",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                }
            ],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "RecordStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "SessionStructure",
                    "name": "currentSession",
                    "id": 1
                },
                {
                    "rule": "repeated",
                    "options": {},
                    "type": "SessionStructure",
                    "name": "previousSessions",
                    "id": 2
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "PreKeyRecordStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "id",
                    "id": 1
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "publicKey",
                    "id": 2
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "privateKey",
                    "id": 3
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "SignedPreKeyRecordStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "id",
                    "id": 1
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "publicKey",
                    "id": 2
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "privateKey",
                    "id": 3
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "signature",
                    "id": 4
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "fixed64",
                    "name": "timestamp",
                    "id": 5
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "IdentityKeyPairStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "publicKey",
                    "id": 1
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "bytes",
                    "name": "privateKey",
                    "id": 2
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "SenderKeyStateStructure",
            "fields": [
                {
                    "rule": "optional",
                    "options": {},
                    "type": "uint32",
                    "name": "senderKeyId",
                    "id": 1
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "SenderChainKey",
                    "name": "senderChainKey",
                    "id": 2
                },
                {
                    "rule": "optional",
                    "options": {},
                    "type": "SenderSigningKey",
                    "name": "senderSigningKey",
                    "id": 3
                },
                {
                    "rule": "repeated",
                    "options": {},
                    "type": "SenderMessageKey",
                    "name": "senderMessageKeys",
                    "id": 4
                }
            ],
            "enums": [],
            "messages": [
                {
                    "name": "SenderChainKey",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "uint32",
                            "name": "iteration",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "seed",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "SenderMessageKey",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "uint32",
                            "name": "iteration",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "seed",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                },
                {
                    "name": "SenderSigningKey",
                    "fields": [
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "public",
                            "id": 1
                        },
                        {
                            "rule": "optional",
                            "options": {},
                            "type": "bytes",
                            "name": "private",
                            "id": 2
                        }
                    ],
                    "enums": [],
                    "messages": [],
                    "options": {},
                    "oneofs": {}
                }
            ],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "SenderKeyRecordStructure",
            "fields": [
                {
                    "rule": "repeated",
                    "options": {},
                    "type": "SenderKeyStateStructure",
                    "name": "senderKeyStates",
                    "id": 1
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        },
        {
            "name": "Session",
            "fields": [
                {
                    "rule": "repeated",
                    "options": {},
                    "type": "SessionStructure",
                    "name": "states",
                    "id": 1
                }
            ],
            "enums": [],
            "messages": [],
            "options": {},
            "oneofs": {}
        }
    ],
    "enums": [],
    "imports": [],
    "options": {
        "java_package": "org.whispersystems.libaxolotl.state",
        "java_outer_classname": "SessionProtos"
    },
    "services": []
}).build("textsecure");
